### ISSUE TITLE
base64 barcode in controller js

### ISSUE THREAD

**Issue by lucav90** [LoicMahieu/angular-io-barcode#5]
Hi,

i want only base64 of barcode in my controller.js

How can i do this?

Regards,

**Comment by LoicMahieu** [comment]
Hi

Not sure to understand the question. Do you want to get the rendered barcode image in base64 ?
If yes, it is out of scope of this package. You could use [`io-barcode`](https://github.com/wavded/io-barcode) which is the underlying barcode rendering engine.

Best regards,
